### PR TITLE
Update to django 1.11

### PR DESCRIPTION
**Pull request by numahell**
Update to django 1.11
* update requirements
* fix impors errors
* fix warnings deprecated when tests passed
* add on_delete in models in a dedicated commit if you need to revert it

### CODE REVIEW

**Comment by numahell** [comment]
Don't know why Travis checks have failed, "chez moi ça marche", even with the same manual command (through docker)
```
docker-compose run --rm web py.test --ds=tests.settings
```

**Comment by harmo** [comment]
@numahell 
https://docs.djangoproject.com/fr/1.11/ref/middleware/#module-django.contrib.auth.middleware
I think `SessionAuthenticationMiddleware` no longer exists

**Comment by numahell** [comment]
True, but I modified it.

**Edit:** I may have forgottent to commit this.

When I run tests as below, I only have some deprecated warnings on Debug toolbar module:
```
Test session starts (platform: linux, Python 3.5.4, pytest 3.3.1, pytest-sugar 0.9.0)
Django settings: tests.settings (from command line option)
rootdir: /usr/src/app, inifile: pytest.ini
plugins: sugar-0.9.0, pep8-1.0.6, django-3.1.2

 dicodigital/dico/tests/test_definitions.py ✓✓✓✓✓✓✓✓✓✓✓✓                                                                                                                 26% ██▋       
 dicodigital/dico/tests/test_votes.py ✓✓✓✓✓✓✓✓✓✓✓                                                                                                                        49% ████▉     
 dicodigital/dico/tests/test_words.py ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓                                                                                                          100% ██████████
================================================================================== warnings summary ===================================================================================
dicodigital/dico/tests/test_definitions.py::TestDefinitionCreate::test_add_definition_to_existant_word
  /venv/lib/python3.5/site-packages/debug_toolbar/settings.py:66: DeprecationWarning: HIDE_DJANGO_SQL was removed. Update your DEBUG_TOOLBAR_CONFIG setting.
    "DEBUG_TOOLBAR_CONFIG setting.", DeprecationWarning)
  /venv/lib/python3.5/site-packages/debug_toolbar/settings.py:82: DeprecationWarning: INTERCEPT_REDIRECTS is deprecated. Please use the DISABLE_PANELS config in the DEBUG_TOOLBAR_CONFIG setting.
    "DEBUG_TOOLBAR_CONFIG setting.", DeprecationWarning)

-- Docs: http://doc.pytest.org/en/latest/warnings.html

Results (2.18s):
      47 passed
```

**Comment by harmo** [comment]
django-debug-toolbar is a dev util, not concerned here ;)

**Comment by numahell** [comment]
Ok I've *really* removed this non existent middleware :)

**Pull request merged**
